fix json format

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -149,8 +149,6 @@ jobs:
         run:
           # To understand the need for /*/*, see comment in "upload artifacts" step above
           gh release upload ${{ env.PRE_RELEASE_NAME }} packages/*/* --repo newrelic/fluent-bit-package
-
-
   notify:
     runs-on: ubuntu-latest
     needs: [ upload_official_packages_to_prerelease, setup_environment ]
@@ -158,12 +156,23 @@ jobs:
       - name: Fetch artifacts
         id: fetch_artifacts
         run: |
-          RELEASE_ID=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/newrelic/fluent-bit-package/releases | jq --arg tag "${{ needs.setup_environment.outputs.pre_release_name }}" '.[] | select(.tag_name==$tag) | .id')
-          ARTIFACTS=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/newrelic/fluent-bit-package/releases/$RELEASE_ID/assets | jq -r '[.[] | select(.name | test("^(fb|fluent-bit)")) | {name: .name, url: .browser_download_url}] | @json')
-          ARTIFACTS_LIST=$(echo "$ARTIFACTS" | jq '.')
+          RELEASE_ID=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/newrelic/fluent-bit-package/releases" | jq --arg tag "${{ needs.setup_environment.outputs.pre_release_name }}" '.[] | select(.tag_name==$tag) | .id')
+          echo "$RELEASE_ID"
+          if [ -z "$RELEASE_ID" ]; then
+            echo "Failed to retrieve release ID for tag: $PRE_RELEASE_NAME"
+            exit 1
+          fi
+          ARTIFACTS=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/newrelic/fluent-bit-package/releases/$RELEASE_ID/assets" | jq -r '[.[] | select(.name | test("^(fb|fluent-bit)")) | {name: .name, url: .browser_download_url}] | @json')
           if [ $? -ne 0 ]; then
             echo "Failed to parse JSON."
             exit 1
+          fi
+          echo "$ARTIFACTS"
+          ARTIFACTS_LIST=$(echo "$ARTIFACTS" | jq '.')
+          echo "$ARTIFACTS_LIST"
+          if [ $? -ne 0 ]; then
+            echo "Failed to parse ARTIFACTS_LIST."
+          exit 1
           fi
           echo "artifacts=$ARTIFACTS_LIST" >> "$GITHUB_OUTPUT"
 
