testing sles skip build option

diff --git a/.github/workflows/run_prerelease.yml b/.github/workflows/run_prerelease.yml
--- a/.github/workflows/run_prerelease.yml
+++ b/.github/workflows/run_prerelease.yml
@@ -109,19 +109,20 @@ jobs:
     steps:
       - name: sles build optional
         run: |
-          echo "Processing SLES Matrix"
-          echo "${{ inputs.sles_matrix }}" > matrix.json
-          is_sles_present=""
-          for row in $(jq -c '.[]' matrix.json); do
+          is_sles_present=true
+          for row in $(echo "$sles_matrix" | jq -c '.[]'); do
             is_staging=$(echo $row | jq '.isStaging')
-            if [[ $is_staging == "true" ]]; then
-              is_sles_present+=" && true"
+            echo "is_staging=${is_staging}"
+            if [ "$is_staging" != "true" ]; then
+              is_sles_present=false
+              break
+            elif [ "$is_staging" == "true" ]; then
+              continue
             else
-              is_sles_present+=" && false"
+               exit 1
             fi
-          done
-          echo "is_sles_present=${is_sles_present}" >> $GITHUB_ENV
-          
+            done
+          echo "is_sles_present=$is_sles_present" >> "$GITHUB_OUTPUT"      
 
   spin_up_suse:
     needs : check_sles_build_optional
@@ -175,89 +176,89 @@ jobs:
         run:
           gh release upload ${{ inputs.pre_release_name }} packages/* --clobber
 
-  provision_and_execute_tests_linux:
-    name:  Provision instances and run tests for linux
-    needs: [ spin_up_test_executor_instances, sign_suse_packages, tear_down_suse ]
-    if: ${{ always() && !failure() && !cancelled()
-      && (needs.spin_up_test_executor_instances.result == 'success' || needs.spin_up_test_executor_instances.result == 'skipped')
-      && (needs.sign_suse_packages.result == 'success' || needs.sign_suse_packages.result == 'skipped')}}
-    uses: ./.github/workflows/run_task.yml
-    with:
-      container_make_target: "ansible/provision-and-execute-tests/${{ inputs.infra_agent_env }}-linux PRE_RELEASE_NAME=${{ inputs.gh_release_name }} TEST_REPORT_NAME=${{ inputs.linux_test_report_name }}"
-    secrets: inherit
-
-  provision_and_execute_tests_windows:
-    name: Provision instances and run tests for windows
-    needs: spin_up_test_executor_instances
-    if: ${{ (needs.spin_up_test_executor_instances.result == 'success' || needs.spin_up_test_executor_instances.result == 'skipped') && ( inputs.windows_matrix != '[]' ) }}
-    uses: ./.github/workflows/run_task.yml
-    with:
-      container_make_target: "ansible/provision-and-execute-tests/${{ inputs.infra_agent_env }}-windows PRE_RELEASE_NAME=${{ inputs.gh_release_name }} TEST_REPORT_NAME=${{ inputs.windows_test_report_name }}"
-    secrets: inherit
-
-  report_linux_test_results:
-    name: Report results linux
-    runs-on: ubuntu-20.04
-    needs: [ provision_and_execute_tests_linux ]
-    if : ${{ always() && !failure() && !cancelled() && (needs.provision_and_execute_tests_linux.result == 'success')}}
-    env:
-      GH_TOKEN: ${{ github.token }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Download report from pre-release # not ok
-        run: |
-          gh release download ${{ inputs.gh_release_name }} --pattern ${{ inputs.linux_test_report_name }}
-
-      - name: Tests Report Details Linux # ok
-        uses: dorny/test-reporter@v1
-        with:
-          name: Tests Report Details  # Name of the check run which will be created
-          path: ${{ inputs.linux_test_report_name }} # Path to test results
-          reporter: jest-junit
-
-      - name: Tests Report Summary Linux # ok
-        uses: EnricoMi/publish-unit-test-result-action@v2
-        if: always()
-        with:
-          files: |
-            ${{ inputs.linux_test_report_name }}
-
-  report_windows_test_results:
-    name: Report results windows
-    runs-on: ubuntu-20.04
-    needs: [ provision_and_execute_tests_windows ]
-    if: ${{ inputs.windows_matrix != '[]' }}
-    env:
-      GH_TOKEN: ${{ github.token }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Download report from pre-release # not ok
-        run: |
-          gh release download ${{ inputs.gh_release_name }} --pattern ${{ inputs.windows_test_report_name }}
-
-      - name: Tests Report Details Windows # ok
-        uses: dorny/test-reporter@v1
-        with:
-          name: Tests Report Details  # Name of the check run which will be created
-          path: ${{ inputs.windows_test_report_name }} # Path to test results
-          reporter: jest-junit
-
-      - name: Tests Report Summary Windows # ok
-        uses: EnricoMi/publish-unit-test-result-action@v2
-        if: always()
-        with:
-          files: |
-            ${{ inputs.windows_test_report_name }}
-
-  tear_down_test_executor_instances:
-    name: Tear down test executor instances
-    if: always()
-    needs: [ report_windows_test_results, report_linux_test_results ]
-    uses: ./.github/workflows/run_task.yml
-    with:
-      container_make_target: "terraform/ec2-test-executors/clean PRE_RELEASE_NAME=${{ inputs.gh_release_name }}"
-    secrets: inherit
+#  provision_and_execute_tests_linux:
+#    name:  Provision instances and run tests for linux
+#    needs: [ spin_up_test_executor_instances, sign_suse_packages, tear_down_suse ]
+#    if: ${{ always() && !failure() && !cancelled()
+#      && (needs.spin_up_test_executor_instances.result == 'success' || needs.spin_up_test_executor_instances.result == 'skipped')
+#      && (needs.sign_suse_packages.result == 'success' || needs.sign_suse_packages.result == 'skipped')}}
+#    uses: ./.github/workflows/run_task.yml
+#    with:
+#      container_make_target: "ansible/provision-and-execute-tests/${{ inputs.infra_agent_env }}-linux PRE_RELEASE_NAME=${{ inputs.gh_release_name }} TEST_REPORT_NAME=${{ inputs.linux_test_report_name }}"
+#    secrets: inherit
+#
+#  provision_and_execute_tests_windows:
+#    name: Provision instances and run tests for windows
+#    needs: spin_up_test_executor_instances
+#    if: ${{ (needs.spin_up_test_executor_instances.result == 'success' || needs.spin_up_test_executor_instances.result == 'skipped') && ( inputs.windows_matrix != '[]' ) }}
+#    uses: ./.github/workflows/run_task.yml
+#    with:
+#      container_make_target: "ansible/provision-and-execute-tests/${{ inputs.infra_agent_env }}-windows PRE_RELEASE_NAME=${{ inputs.gh_release_name }} TEST_REPORT_NAME=${{ inputs.windows_test_report_name }}"
+#    secrets: inherit
+#
+#  report_linux_test_results:
+#    name: Report results linux
+#    runs-on: ubuntu-20.04
+#    needs: [ provision_and_execute_tests_linux ]
+#    if : ${{ always() && !failure() && !cancelled() && (needs.provision_and_execute_tests_linux.result == 'success')}}
+#    env:
+#      GH_TOKEN: ${{ github.token }}
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#
+#      - name: Download report from pre-release # not ok
+#        run: |
+#          gh release download ${{ inputs.gh_release_name }} --pattern ${{ inputs.linux_test_report_name }}
+#
+#      - name: Tests Report Details Linux # ok
+#        uses: dorny/test-reporter@v1
+#        with:
+#          name: Tests Report Details  # Name of the check run which will be created
+#          path: ${{ inputs.linux_test_report_name }} # Path to test results
+#          reporter: jest-junit
+#
+#      - name: Tests Report Summary Linux # ok
+#        uses: EnricoMi/publish-unit-test-result-action@v2
+#        if: always()
+#        with:
+#          files: |
+#            ${{ inputs.linux_test_report_name }}
+#
+#  report_windows_test_results:
+#    name: Report results windows
+#    runs-on: ubuntu-20.04
+#    needs: [ provision_and_execute_tests_windows ]
+#    if: ${{ inputs.windows_matrix != '[]' }}
+#    env:
+#      GH_TOKEN: ${{ github.token }}
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#
+#      - name: Download report from pre-release # not ok
+#        run: |
+#          gh release download ${{ inputs.gh_release_name }} --pattern ${{ inputs.windows_test_report_name }}
+#
+#      - name: Tests Report Details Windows # ok
+#        uses: dorny/test-reporter@v1
+#        with:
+#          name: Tests Report Details  # Name of the check run which will be created
+#          path: ${{ inputs.windows_test_report_name }} # Path to test results
+#          reporter: jest-junit
+#
+#      - name: Tests Report Summary Windows # ok
+#        uses: EnricoMi/publish-unit-test-result-action@v2
+#        if: always()
+#        with:
+#          files: |
+#            ${{ inputs.windows_test_report_name }}
+#
+#  tear_down_test_executor_instances:
+#    name: Tear down test executor instances
+#    if: always()
+#    needs: [ report_windows_test_results, report_linux_test_results ]
+#    uses: ./.github/workflows/run_task.yml
+#    with:
+#      container_make_target: "terraform/ec2-test-executors/clean PRE_RELEASE_NAME=${{ inputs.gh_release_name }}"
+#    secrets: inherit
